language: go

go:
  - tip

addons:
  apt:
    packages:
      - geoip-bin
      - libgeoip-dev

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/handlers
  - go get github.com/fzzy/radix/redis
  - go get github.com/abh/geoip